name: ldm
channels:
  - nvidia/label/cuda-11.7.1
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.10
  - pip
  - nvidia::cudatoolkit=11.7
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - torchvision
  - numpy
  - xformers/label/dev::xformers
  - pip:
    - aiohttp
    - bitsandbytes==0.35.0
    - colorama
    - diffusers[torch]
    - ftfy
    - ninja
    - omegaconf
    - piexif
    - protobuf
    - pynvml
    - pyre-extensions
    - pytorch-lightning
    - tensorboard
    - transformers==4.25.1
    - wandb
