name: ldm
channels:
  - nvidia/label/cuda-11.7.1
  - pytorch
  - defaults
dependencies:
  - git
  - python=3.10
  - pip
  - nvidia::cudatoolkit=11.7
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  - torchvision
  - numpy
  - xformers/label/dev::xformers
  - pip:
    - aiohttp==3.8.3
    - bitsandbytes==0.35.0
    - charset-normalizer==3.0.1
    - cmake==3.25.2
    - colorama
    - diffusers[torch]==0.12.1
    - ftfy==6.1.1
    - ninja
    - numpy==1.24.2
    - omegaconf==2.2.3
    - piexif==1.1.3
    - protobuf==3.20.3
    - pynvml
    - pyre-extensions
    - pytorch-lightning==1.7.6
    - requests==2.28.2
    - tensorboard==2.11.0
    - transformers==4.25.1
    - wandb
